;;; company-glsl-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from company-glsl.el

(autoload 'company-glsl "company-glsl" "\
Provide GLSL completion info according to prefix COMMAND and ARG.  IGNORED is not used.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-glsl" '("company-glsl--"))

;;; End of scraped data

(provide 'company-glsl-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-glsl-autoloads.el ends here
